package it.polimi.se2018.model;

public enum CommandTypeEnum {
    NICKNAME, TYPEOFCHOICE, TOOLCARDID, DICEBOARDINDEX, DICESCHEMAWHERETOTAKE, DICESCHEMAWHERETOLEAVE, TRACKBOARDINDEX, VALUE, IDSCHEMA, FRAMECOLOUR, COMPLETE
}
